apiVersion: v1
kind: Pod
metadata:
  name: tensorflow-eval
  labels:
    app: tensorflow-eval
spec:
  containers:
    - image: banzaicloud/tensorflow-inception-example:v0.18-gpu
      name: tensorflow-eval
      command: ["bazel-bin/inception/imagenet_eval"]
      args: ["--checkpoint_dir=/efs/train", "--eval_dir=/efs/eval", "--data_dir=/efs/image-data", "--num_gpus=1", "--subset=validation"]
      volumeMounts:
          - name: efs-pvc
            mountPath: "/efs"
          - name: bin
            mountPath: /usr/local/nvidia/bin
          - name: lib
            mountPath: /usr/local/nvidia/lib64
          - name: libcuda
            mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so.1
        resources:
          requests:
            alpha.kubernetes.io/nvidia-gpu: 1
          limits:
            alpha.kubernetes.io/nvidia-gpu: 1
            
  volumes:
    - name: efs-pvc
      persistentVolumeClaim:
        claimName: azure-files
    - name: bin
      hostPath:
        path: /usr/lib/nvidia-384/bin
    - name: lib
      hostPath:
        path: /usr/lib/nvidia-384
    - name: libcuda
      hostPath:
        path: /usr/lib/x86_64-linux-gnu/libcuda.so.1
