apiVersion: v1
kind: Pod
metadata:
  name: tensorflow-prepare
  labels:
    app: tensorflow-prepare
spec:
  containers:
  - name: tensorflow-prepare
    image: banzaicloud/tensorflow-inception-example:v0.1
    command: ["bazel-bin/inception/download_and_preprocess_flowers"]
    args: ["/efs/image-data"]
    volumeMounts:
        - name: efs-pvc
          mountPath: "/efs"
  restartPolicy: "Never"
  volumes:
    - name: efs-pvc
      persistentVolumeClaim:
        claimName: efs
