---
apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
type: Opaque
data:
  azurestorageaccountkey: {STORAGE_ACCOUNT_KEY_BASE64_ENCODED}
  azurestorageaccountname: {STORAGE_ACCOUNT_NAME_BASE64_ENCODED}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: azure-secret
    shareName: tensorflowshared
    readOnly: false
  claimRef:
    namespace: default
    name: azure-files
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-files
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
